// Generated by staged-semantic-typescript-mvp. Do not edit.
import type { StorefrontOrder } from "./semantic";

/** Definition: An order eligible to enter the physical-fulfillment intake stage under the requirements and exclusions below. Requirements: - The concrete schema's authoritative payment or authorization state is confirmed. - A delivery destination value is present (not null or undefined). Exclusions: - Orders with an active cancellation state. - Orders with an active hold state. - Orders with an active void state. Out of scope: - Inventory quantity or availability. - Carrier availability. - Delivery timing. - Price. Leave unresolved when: - The payment or authorization role cannot be mapped uniquely from the supplied type. - The cancellation, hold, or void role cannot be mapped uniquely from the supplied type. - The delivery destination role cannot be mapped uniquely from the supplied type. */
export function isFulfillableStorefrontOrder(
  storefrontOrder: StorefrontOrder,
): boolean {
  return (
    storefrontOrder.paymentStatus === "paid" &&
    storefrontOrder.cancelledAt === null &&
    (storefrontOrder.shippingAddress !== null && storefrontOrder.shippingAddress !== undefined)
  );
}
