// Generated by staged-semantic-typescript-mvp. Do not edit.
import type { Customer } from "./semantic";

/** Definition: A customer that is currently active and contactable. Requirements: - status is "active". - deletedAt is null. - email is present. Exclusions: - Customers whose status is "suspended". - Customers whose deletedAt is not null. Out of scope: - Email address syntax and deliverability. Leave unresolved when: - The schema does not expose status, deletion, or email roles unambiguously. */
export function isActiveCustomer(
  customer: Customer,
): boolean {
  return (
    customer.status === "active" &&
    customer.deletedAt === null &&
    (customer.email !== null && customer.email !== undefined)
  );
}
