// Generated by staged-semantic-typescript-mvp. Do not edit.
import type { Customer } from "./semantic";

/** An active customer has status "active", has not been deleted (deletedAt is null), and has a present email address. */
export function isActiveCustomer(
  customer: Customer,
): boolean {
  return (
    customer.status === "active" &&
    customer.deletedAt === null &&
    (customer.email !== null && customer.email !== undefined)
  );
}
