// Generated by staged-semantic-typescript-mvp. Do not edit.
import type { CustomerRecord } from "./semantic";

/** A customer that is currently permitted to use the service. The concrete schema's authoritative availability state permits service, no exclusion state represented by that schema is active, and a usable contact address is present. Schemas may encode availability and exclusion differently. Use only roles that are unambiguously represented by the supplied type. If those roles cannot be mapped without guessing, leave the concept unresolved. */
export function isActiveCustomerRecord(
  customerRecord: CustomerRecord,
): boolean {
  return (
    customerRecord.status === "active" &&
    customerRecord.deletedAt === null &&
    (customerRecord.email !== null && customerRecord.email !== undefined)
  );
}
