import type { PredicateDefinition, PredicateExpression } from "./ir";

export function generatePredicate(definition: PredicateDefinition): string {
  const expression = renderPredicateExpression(
    definition.body,
    definition.input.parameter,
    1,
  );

  return [
    "// Generated by staged-semantic-typescript-mvp. Do not edit.",
    `import type { ${definition.input.type} } from ${JSON.stringify(definition.input.module)};`,
    "",
    `/** ${sanitizeComment(definition.description)} */`,
    `export function ${definition.name}(`,
    `  ${definition.input.parameter}: ${definition.input.type},`,
    `): ${definition.returns} {`,
    `  return ${expression};`,
    "}",
    "",
  ].join("\n");
}

export function renderPredicateExpression(
  expression: PredicateExpression,
  parameter: string,
  depth: number,
  renderProperty: (
    parameter: string,
    property: string[],
  ) => string = renderDirectProperty,
): string {
  switch (expression.kind) {
    case "all":
    case "any": {
      const operator = expression.kind === "all" ? "&&" : "||";
      const childIndentation = "  ".repeat(depth + 1);
      const closingIndentation = "  ".repeat(depth);

      const rendered = expression.conditions
        .map((condition) =>
          renderPredicateExpression(
            condition,
            parameter,
            depth + 1,
            renderProperty,
          ),
        )
        .join(` ${operator}\n${childIndentation}`);

      return `(\n${childIndentation}${rendered}\n${closingIndentation})`;
    }
    case "not":
      return `!(${renderPredicateExpression(expression.condition, parameter, depth + 1, renderProperty)})`;
    case "equals":
      return `${renderProperty(parameter, expression.property)} === ${JSON.stringify(expression.value)}`;
    case "present": {
      const property = renderProperty(parameter, expression.property);
      return `(${property} !== null && ${property} !== undefined)`;
    }
  }
}

function renderDirectProperty(parameter: string, property: string[]): string {
  return [parameter, ...property].join(".");
}

function sanitizeComment(value: string): string {
  return value.replaceAll("*/", "*\\/").replaceAll(/\s+/g, " ").trim();
}
