import {
  lstat,
  mkdir,
  readFile,
  rename,
  rmdir,
  unlink,
  writeFile,
} from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import ts from "typescript";
import { resolveContainedFile } from "./contained-path";
import {
  effectValueTypeJson,
  encodeEffectValue,
  parseEffectValueType,
  type TypedEffectNode,
} from "./llang-effects-ir";
import {
  emitTypedEffectsWasm,
  type TypedEffectsWasmContract,
} from "./llang-effects-state-machine";
import {
  assertEffectsWasm,
  type EffectsWasmContract,
  emitLinearEffectsWasm,
} from "./llang-effects-wasm";
import { parseStrictJsonObject } from "./llang-jsonc";
import {
  type CheckedEffectsModuleProgram,
  loadEffectsModuleProgram,
} from "./llang-module-effects-loader";
import {
  loadEffectsModuleGraph,
  type CheckedEffectsGraph,
} from "./llang-module-effects-graph";
import {
  emitEffectsModuleJsonc,
  emitEffectsModuleTypeScript,
} from "./llang-module-effects-source-emitter";
import { fingerprintFor } from "./stable-hash";
import { digest } from "./wasm-contract";

export type EffectsModuleTarget = "typescript" | "jsonc" | "wasm";
export type EffectsModuleBuildManifest = Readonly<{
  format: "llang-module-build";
  version: 5;
  profile: "module-effects-v1";
  abi: "llang-effects-session-v1";
  entry: string;
  sourceSetHash: string;
  programHash: string;
  loweredHash: string;
  interfaceHash: string;
  resultType?: unknown;
  operations: CheckedEffectsModuleProgram["manifest"]["operations"];
  effects: CheckedEffectsModuleProgram["manifest"]["effects"];
  resources: Readonly<{
    memoryPages: 512;
    wireBytes: 2_097_152;
    chunkBytes: 65_536;
    hostRequests: 1_024;
    tasks: 1_024;
    fuel: 10_000_000;
  }>;
  sources: readonly Readonly<{ path: string; hash: string }>[];
  targets: readonly EffectsModuleTarget[];
  artifacts: readonly Readonly<{ path: string; hash: string; bytes: number }>[];
  wasm?: Readonly<{
    path: "wasm/program.wasm";
    contract: EffectsWasmContract | TypedEffectsWasmContract;
    wasmHash: string;
    states?: readonly Readonly<{
      kind: "await" | "task" | "stream";
      operation: number;
      requestType: unknown;
      responseType: unknown;
    }>[];
  }>;
  toolchain: Readonly<{
    compiler: "0.1.0-dev.1";
    binaryen: "132.0.0";
    typescript: "5.9.3";
  }>;
}>;

const graphNodeJson = (node: TypedEffectNode): unknown => {
  if (node.kind === "task")
    return {
      kind: "task",
      tasks: node.tasks.map((task) => ({
        kind: "await",
        operation: task.operation,
        version: task.version,
        request: encodeEffectValue(task.requestType, task.request),
      })),
    };
  return {
    kind: node.kind,
    operation: node.operation,
    version: node.version,
    request: encodeEffectValue(node.requestType, node.request),
    ...(node.kind === "stream" ? { maximumChunks: node.maximumChunks } : {}),
  };
};

const flattenedGraphSource = (graph: CheckedEffectsGraph) => {
  const [moduleName, entryName] = graph.entry.split("#") as [string, string];
  return {
    language: "l-lang" as const,
    version: 5 as const,
    kind: "module" as const,
    profile: "module-effects-v1" as const,
    module: moduleName,
    entry: entryName,
    imports: [],
    operations: graph.operations.filter((operation) =>
      graph.manifest.operations.some(
        (requirement) =>
          requirement.id === operation.id &&
          requirement.version === operation.version,
      ),
    ),
    resultType: effectValueTypeJson(graph.program.resultType),
    nodes: graph.program.nodes.map(graphNodeJson),
  };
};

const emitGraphTypeScript = (graph: CheckedEffectsGraph): string => {
  const source = flattenedGraphSource(graph),
    { entry, ...definition } = source;
  return `// Generated by L-Lang module-effects-v1. Do not edit.
const defineEffects = <T>(definition: T): Readonly<T> => Object.freeze(definition);
export const ${entry} = defineEffects(${JSON.stringify(definition, null, 2)} as const);
type AwaitNode = Readonly<{ kind: "await" | "stream"; operation: string; version: number; request: unknown }>;
type TaskNode = Readonly<{ kind: "task"; tasks: readonly AwaitNode[] }>;
type EffectNode = AwaitNode | TaskNode;
export interface EffectsHost {
  invoke(request: Readonly<{ kind: "await" | "stream"; operation: string; version: number; payload: unknown }>): Promise<unknown>;
}
const invoke = (host: EffectsHost, node: AwaitNode) => host.invoke({ kind: node.kind, operation: node.operation, version: node.version, payload: node.request });
export async function execute(host: EffectsHost): Promise<unknown> {
  let result: unknown;
  for (const node of ${entry}.nodes as readonly EffectNode[])
    result = node.kind === "task"
      ? await Promise.all(node.tasks.map((task) => invoke(host, task)))
      : await invoke(host, node);
  return result;
}
`;
};

async function buildEffectsModuleGraphProgram(
  graph: CheckedEffectsGraph,
  options: {
    target?: EffectsModuleTarget | "all";
    outDir: string;
  },
): Promise<EffectsModuleBuildManifest> {
  const out = resolve(options.outDir),
    targets: EffectsModuleTarget[] =
      options.target && options.target !== "all"
        ? [options.target]
        : ["typescript", "jsonc", "wasm"],
    artifacts: { path: string; hash: string; bytes: number }[] = [],
    createdPaths: string[] = [];
  await mkdir(out);
  try {
    if (targets.includes("typescript")) {
      const path = "typescript/program.generated.ts";
      await writeArtifact(out, path, emitGraphTypeScript(graph), artifacts);
      createdPaths.push(path);
      verifyGeneratedTypeScript(join(out, path));
    }
    if (targets.includes("jsonc")) {
      const path = "jsonc/program.llang.jsonc";
      await writeArtifact(
        out,
        path,
        `${JSON.stringify(flattenedGraphSource(graph), null, 2)}\n`,
        artifacts,
      );
      createdPaths.push(path);
    }
    const emitted = emitTypedEffectsWasm(
        graph.program,
        graph.manifest.operations,
      ),
      loweredHash = emitted.contract.programHash;
    let wasm: EffectsModuleBuildManifest["wasm"];
    if (targets.includes("wasm")) {
      const path = "wasm/program.wasm",
        wasmHash = digest(emitted.bytes);
      assertEffectsWasm(emitted.bytes);
      await writeArtifact(out, path, emitted.bytes, artifacts);
      createdPaths.push(path);
      wasm = {
        path,
        contract: emitted.contract,
        wasmHash,
        states: Object.freeze(
          emitted.states.map((state) =>
            Object.freeze({
              kind: state.kind,
              operation: state.operation,
              requestType: effectValueTypeJson(state.requestType),
              responseType: effectValueTypeJson(state.responseType),
            }),
          ),
        ),
      };
    }
    artifacts.sort((a, b) => a.path.localeCompare(b.path));
    const manifest: EffectsModuleBuildManifest = Object.freeze({
      format: "llang-module-build",
      version: 5,
      profile: "module-effects-v1",
      abi: "llang-effects-session-v1",
      entry: graph.entry,
      sourceSetHash: graph.sourceSetHash,
      programHash: graph.programHash,
      loweredHash,
      interfaceHash: graph.interfaceHash,
      resultType: effectValueTypeJson(graph.program.resultType),
      operations: graph.manifest.operations,
      effects: graph.manifest.effects,
      resources: {
        memoryPages: 512,
        wireBytes: 2_097_152,
        chunkBytes: 65_536,
        hostRequests: 1_024,
        tasks: 1_024,
        fuel: 10_000_000,
      },
      sources: graph.sources,
      targets: Object.freeze(targets),
      artifacts: Object.freeze(artifacts),
      ...(wasm ? { wasm } : {}),
      toolchain: {
        compiler: "0.1.0-dev.1",
        binaryen: "132.0.0",
        typescript: "5.9.3",
      },
    });
    const temporary = join(out, ".module-build.json.tmp");
    await writeFile(temporary, `${JSON.stringify(manifest, null, 2)}\n`, {
      flag: "wx",
    });
    await rename(temporary, join(out, "module-build.json"));
    createdPaths.push("module-build.json");
    return manifest;
  } catch (error) {
    for (const path of [".module-build.json.tmp", ...createdPaths].reverse())
      await unlink(join(out, path)).catch(() => undefined);
    for (const directory of ["typescript", "jsonc", "wasm"])
      await rmdir(join(out, directory)).catch(() => undefined);
    await rmdir(out).catch(() => undefined);
    throw error;
  }
}

const writeArtifact = async (
  root: string,
  path: string,
  value: string | Uint8Array,
  artifacts: { path: string; hash: string; bytes: number }[],
) => {
  const absolute = join(root, path),
    bytes = typeof value === "string" ? new TextEncoder().encode(value) : value;
  await mkdir(dirname(absolute), { recursive: true });
  await writeFile(absolute, value, { flag: "wx" });
  artifacts.push({ path, hash: digest(bytes), bytes: bytes.length });
};

const verifyGeneratedTypeScript = (path: string) => {
  const diagnostics = ts.getPreEmitDiagnostics(
    ts.createProgram([path], {
      strict: true,
      noEmit: true,
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      skipLibCheck: true,
      types: [],
      noResolve: true,
    }),
  );
  const diagnostic = diagnostics[0];
  if (diagnostic)
    throw new Error(
      `generated TypeScript failed typecheck: ${ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n")}`,
    );
};

export async function buildEffectsModuleProgram(options: {
  entry: string;
  root: string;
  entryName: string;
  target?: EffectsModuleTarget | "all";
  outDir: string;
}): Promise<EffectsModuleBuildManifest> {
  const sourcePath = await resolveContainedFile(
      resolve(options.root),
      options.entry,
      "effects source",
      { rejectSymbolicLinks: true },
    ),
    sourceText = await readFile(sourcePath, "utf8");
  if (/(?:"nodes"|\bnodes)\s*:/.test(sourceText)) {
    const graph = await loadEffectsModuleGraph(
      options.entry,
      options.root,
      options.entryName,
    );
    return buildEffectsModuleGraphProgram(graph, options);
  }
  const program = await loadEffectsModuleProgram(
      options.entry,
      options.root,
      options.entryName,
    ),
    out = resolve(options.outDir),
    loweredHash = fingerprintFor({ program: program.program });
  await mkdir(out);
  const createdPaths: string[] = [];
  try {
    const targets: EffectsModuleTarget[] =
        options.target && options.target !== "all"
          ? [options.target]
          : ["typescript", "jsonc", "wasm"],
      artifacts: { path: string; hash: string; bytes: number }[] = [];
    if (targets.includes("typescript")) {
      const path = "typescript/program.generated.ts";
      await writeArtifact(
        out,
        path,
        emitEffectsModuleTypeScript(program),
        artifacts,
      );
      createdPaths.push(path);
      verifyGeneratedTypeScript(join(out, path));
    }
    if (targets.includes("jsonc")) {
      const path = "jsonc/program.llang.jsonc";
      await writeArtifact(
        out,
        path,
        emitEffectsModuleJsonc(program),
        artifacts,
      );
      createdPaths.push(path);
      const roundTrip = await loadEffectsModuleProgram(
        path,
        out,
        options.entryName,
      );
      if (
        roundTrip.programHash !== program.programHash ||
        roundTrip.interfaceHash !== program.interfaceHash
      )
        throw new Error("generated JSONC round-trip changed program meaning");
    }
    let wasm: EffectsModuleBuildManifest["wasm"];
    if (targets.includes("wasm")) {
      const emitted = emitLinearEffectsWasm(program.program),
        path = "wasm/program.wasm",
        wasmHash = digest(emitted.bytes);
      if (emitted.contract.programHash !== loweredHash)
        throw new Error("effects lowering hash mismatch");
      assertEffectsWasm(emitted.bytes);
      await writeArtifact(out, path, emitted.bytes, artifacts);
      createdPaths.push(path);
      wasm = { path, contract: emitted.contract, wasmHash };
    }
    artifacts.sort((a, b) => a.path.localeCompare(b.path));
    const sourcePath = relative(
        resolve(options.root),
        program.sourcePath,
      ).replaceAll("\\", "/"),
      manifest: EffectsModuleBuildManifest = Object.freeze({
        format: "llang-module-build",
        version: 5,
        profile: "module-effects-v1",
        abi: "llang-effects-session-v1",
        entry: `${program.source.module}#${program.source.entry}`,
        sourceSetHash: program.sourceSetHash,
        programHash: program.programHash,
        loweredHash,
        interfaceHash: program.interfaceHash,
        operations: program.manifest.operations,
        effects: program.manifest.effects,
        resources: {
          memoryPages: 512,
          wireBytes: 2_097_152,
          chunkBytes: 65_536,
          hostRequests: 1_024,
          tasks: 1_024,
          fuel: 10_000_000,
        } as const,
        sources: [{ path: sourcePath, hash: program.sourceHash }],
        targets: Object.freeze(targets),
        artifacts: Object.freeze(artifacts),
        ...(wasm ? { wasm } : {}),
        toolchain: {
          compiler: "0.1.0-dev.1",
          binaryen: "132.0.0",
          typescript: "5.9.3",
        } as const,
      });
    const temporary = join(out, ".module-build.json.tmp");
    await writeFile(temporary, `${JSON.stringify(manifest, null, 2)}\n`, {
      flag: "wx",
    });
    await rename(temporary, join(out, "module-build.json"));
    createdPaths.push("module-build.json");
    return manifest;
  } catch (error) {
    // Never recursively delete a caller-selected path. Remove only files this
    // invocation created; if anything was replaced or added, leave the
    // directory behind for explicit inspection.
    for (const path of [".module-build.json.tmp", ...createdPaths].reverse())
      await unlink(join(out, path)).catch(() => undefined);
    const directories = [
      ...new Set(
        createdPaths
          .map((path) => dirname(path))
          .filter((path) => path !== "."),
      ),
    ].sort((a, b) => b.length - a.length);
    for (const directory of directories)
      await rmdir(join(out, directory)).catch(() => undefined);
    await rmdir(out).catch(() => undefined);
    throw error;
  }
}

const HASH = /^[0-9a-f]{64}$/;
const OPERATION_ID = /^[a-z][A-Za-z0-9]*(?:[._/-][A-Za-z0-9]+)*$/;
const EFFECTS = ["clock", "file", "host", "http"] as const;
const TARGETS = ["typescript", "jsonc", "wasm"] as const;
const object = (value: unknown): value is Record<string, unknown> =>
  !!value && typeof value === "object" && !Array.isArray(value);
const exactKeys = (value: Record<string, unknown>, expected: string[]) =>
  Object.keys(value).length === expected.length &&
  Object.keys(value).every((key) => expected.includes(key));
const safePath = (value: unknown): value is string =>
  typeof value === "string" &&
  value.length > 0 &&
  value.length <= 1024 &&
  !value.startsWith("/") &&
  !value.includes("\\") &&
  !value.split("/").includes("..");

export async function readEffectsModuleBuildManifest(path: string): Promise<{
  manifest: EffectsModuleBuildManifest;
  artifacts: ReadonlyMap<string, Uint8Array>;
}> {
  const absolute = resolve(path),
    info = await lstat(absolute);
  if (!info.isFile() || info.isSymbolicLink() || info.size > 1024 * 1024)
    throw new Error("INVALID_ARTIFACT: effects module manifest");
  const parsed = parseStrictJsonObject(
    await readFile(absolute, "utf8"),
    absolute,
  );
  const manifestKeys = [
    "format",
    "version",
    "profile",
    "abi",
    "entry",
    "sourceSetHash",
    "programHash",
    "loweredHash",
    "interfaceHash",
    "operations",
    "effects",
    "resources",
    "sources",
    "targets",
    "artifacts",
    "toolchain",
  ];
  if (object(parsed) && parsed.resultType !== undefined)
    manifestKeys.push("resultType");
  if (
    object(parsed) &&
    Array.isArray(parsed.targets) &&
    parsed.targets.includes("wasm")
  )
    manifestKeys.push("wasm");
  if (
    !object(parsed) ||
    !exactKeys(parsed, manifestKeys) ||
    parsed.format !== "llang-module-build" ||
    parsed.version !== 5 ||
    parsed.profile !== "module-effects-v1" ||
    parsed.abi !== "llang-effects-session-v1" ||
    typeof parsed.entry !== "string" ||
    !HASH.test(String(parsed.sourceSetHash)) ||
    !HASH.test(String(parsed.programHash)) ||
    !HASH.test(String(parsed.loweredHash)) ||
    !HASH.test(String(parsed.interfaceHash)) ||
    !Array.isArray(parsed.operations) ||
    !Array.isArray(parsed.effects) ||
    !Array.isArray(parsed.sources) ||
    !Array.isArray(parsed.targets) ||
    !parsed.targets.length ||
    new Set(parsed.targets).size !== parsed.targets.length ||
    parsed.targets.some((target) => !TARGETS.includes(target)) ||
    parsed.targets.join() !==
      [...parsed.targets]
        .sort((a, b) => TARGETS.indexOf(a) - TARGETS.indexOf(b))
        .join() ||
    !Array.isArray(parsed.artifacts) ||
    !parsed.artifacts.length ||
    parsed.artifacts.length > 8 ||
    !object(parsed.resources) ||
    !exactKeys(parsed.resources, [
      "memoryPages",
      "wireBytes",
      "chunkBytes",
      "hostRequests",
      "tasks",
      "fuel",
    ]) ||
    parsed.resources.memoryPages !== 512 ||
    parsed.resources.wireBytes !== 2_097_152 ||
    parsed.resources.chunkBytes !== 65_536 ||
    parsed.resources.hostRequests !== 1_024 ||
    parsed.resources.tasks !== 1_024 ||
    parsed.resources.fuel !== 10_000_000 ||
    !object(parsed.toolchain) ||
    !exactKeys(parsed.toolchain, ["compiler", "binaryen", "typescript"]) ||
    parsed.toolchain.compiler !== "0.1.0-dev.1" ||
    parsed.toolchain.binaryen !== "132.0.0" ||
    parsed.toolchain.typescript !== "5.9.3"
  )
    throw new Error("INVALID_ARTIFACT: effects module manifest");
  const entryParts = String(parsed.entry).split("#");
  if (
    entryParts.length !== 2 ||
    !entryParts[0] ||
    !entryParts[1] ||
    !parsed.operations.length ||
    parsed.operations.length > 1024 ||
    parsed.effects.length > EFFECTS.length ||
    new Set(parsed.effects).size !== parsed.effects.length ||
    parsed.effects.some((effect) => !EFFECTS.includes(effect)) ||
    parsed.effects.join() !==
      [...parsed.effects]
        .sort((a, b) => EFFECTS.indexOf(a) - EFFECTS.indexOf(b))
        .join()
  )
    throw new Error("INVALID_ARTIFACT: effects module interface");
  const operationKeys = new Set<string>();
  for (const operation of parsed.operations) {
    if (
      !object(operation) ||
      !exactKeys(operation, ["id", "version", "signatureHash", "effect"]) ||
      typeof operation.id !== "string" ||
      !OPERATION_ID.test(operation.id) ||
      !Number.isInteger(operation.version) ||
      Number(operation.version) < 1 ||
      !HASH.test(String(operation.signatureHash)) ||
      !EFFECTS.some((effect) => effect === operation.effect) ||
      !parsed.effects.includes(operation.effect) ||
      operationKeys.has(`${operation.id}@${operation.version}`)
    )
      throw new Error("INVALID_ARTIFACT: effects module operation");
    operationKeys.add(`${operation.id}@${operation.version}`);
  }
  const sortedOperations = [...parsed.operations].sort((left, right) => {
    if (!object(left) || !object(right)) return 0;
    return left.id === right.id
      ? Number(left.version) - Number(right.version)
      : String(left.id).localeCompare(String(right.id));
  });
  if (
    JSON.stringify(sortedOperations) !== JSON.stringify(parsed.operations) ||
    fingerprintFor({
      profile: parsed.profile,
      entry: entryParts[1],
      ...(parsed.resultType === undefined
        ? { result: "i32" }
        : { resultType: parsed.resultType }),
      effects: parsed.effects,
      operations: parsed.operations,
    }) !== parsed.interfaceHash
  )
    throw new Error("INVALID_ARTIFACT: effects module interface");
  if (!parsed.sources.length || parsed.sources.length > 1024)
    throw new Error("INVALID_ARTIFACT: effects module sources");
  for (const source of parsed.sources)
    if (
      !object(source) ||
      !exactKeys(source, ["path", "hash"]) ||
      !safePath(source.path) ||
      !HASH.test(String(source.hash))
    )
      throw new Error("INVALID_ARTIFACT: effects module source");
  if (
    fingerprintFor(
      parsed.sources.map((source) => ({
        path: object(source) ? source.path : undefined,
        hash: object(source) ? source.hash : undefined,
      })),
    ) !== parsed.sourceSetHash
  )
    throw new Error("INVALID_ARTIFACT: effects source set");
  const seen = new Set<string>();
  for (const artifact of parsed.artifacts) {
    if (
      !object(artifact) ||
      !exactKeys(artifact, ["path", "hash", "bytes"]) ||
      !safePath(artifact.path) ||
      !HASH.test(String(artifact.hash)) ||
      !Number.isInteger(artifact.bytes) ||
      Number(artifact.bytes) < 0 ||
      Number(artifact.bytes) > 64 * 1024 * 1024 ||
      seen.has(artifact.path)
    )
      throw new Error("INVALID_ARTIFACT: effects module artifact");
    seen.add(artifact.path);
  }
  const expectedArtifacts = parsed.targets
    .map((target) =>
      target === "typescript"
        ? "typescript/program.generated.ts"
        : target === "jsonc"
          ? "jsonc/program.llang.jsonc"
          : "wasm/program.wasm",
    )
    .sort();
  if (
    parsed.artifacts
      .map((artifact) => (object(artifact) ? String(artifact.path) : ""))
      .sort()
      .join() !== expectedArtifacts.join()
  )
    throw new Error("INVALID_ARTIFACT: effects module target artifacts");
  if (parsed.targets.includes("wasm")) {
    const typedContract =
      object(parsed.wasm) &&
      object(parsed.wasm.contract) &&
      parsed.wasm.contract.layout === "typed-wire-v1";
    if (
      !object(parsed.wasm) ||
      !exactKeys(
        parsed.wasm,
        typedContract
          ? ["path", "contract", "wasmHash", "states"]
          : ["path", "contract", "wasmHash"],
      ) ||
      parsed.wasm.path !== "wasm/program.wasm" ||
      !HASH.test(String(parsed.wasm.wasmHash)) ||
      !object(parsed.wasm.contract) ||
      !exactKeys(
        parsed.wasm.contract,
        typedContract
          ? [
              "abi",
              "layout",
              "memory",
              "requestBytes",
              "eventBytes",
              "outputBytes",
              "stateCount",
              "programHash",
            ]
          : [
              "abi",
              "memory",
              "requestBytes",
              "eventBytes",
              "outputBytes",
              "programHash",
            ],
      ) ||
      parsed.wasm.contract.abi !== "llang-effects-session-v1" ||
      parsed.wasm.contract.programHash !== parsed.loweredHash ||
      !object(parsed.wasm.contract.memory) ||
      parsed.wasm.contract.memory.initial !== 512 ||
      parsed.wasm.contract.memory.maximum !== 512 ||
      (typedContract
        ? parsed.wasm.contract.requestBytes !== 32 ||
          parsed.wasm.contract.eventBytes !== 24 ||
          parsed.wasm.contract.outputBytes !== 12 ||
          !Number.isInteger(parsed.wasm.contract.stateCount) ||
          Number(parsed.wasm.contract.stateCount) < 1 ||
          Number(parsed.wasm.contract.stateCount) > 1024
        : parsed.wasm.contract.requestBytes !== 16 ||
          parsed.wasm.contract.eventBytes !== 16 ||
          parsed.wasm.contract.outputBytes !== 4)
    )
      throw new Error("INVALID_ARTIFACT: effects Wasm contract");
    if (typedContract) {
      if (
        !Array.isArray(parsed.wasm.states) ||
        parsed.wasm.states.length !== parsed.wasm.contract.stateCount
      )
        throw new Error("INVALID_ARTIFACT: typed effects states");
      for (const state of parsed.wasm.states) {
        if (
          !object(state) ||
          !exactKeys(state, [
            "kind",
            "operation",
            "requestType",
            "responseType",
          ]) ||
          !["await", "task", "stream"].includes(String(state.kind)) ||
          !Number.isInteger(state.operation) ||
          Number(state.operation) < -1 ||
          Number(state.operation) >= parsed.operations.length
        )
          throw new Error("INVALID_ARTIFACT: typed effects state");
        try {
          parseEffectValueType(state.requestType);
          parseEffectValueType(state.responseType);
        } catch {
          throw new Error("INVALID_ARTIFACT: typed effects state");
        }
      }
    }
  } else if (parsed.wasm !== undefined)
    throw new Error("INVALID_ARTIFACT: unexpected effects Wasm");
  const manifest = parsed as unknown as EffectsModuleBuildManifest,
    artifacts = new Map<string, Uint8Array>();
  for (const artifact of manifest.artifacts) {
    const artifactPath = await resolveContainedFile(
        dirname(absolute),
        artifact.path,
        "effects module artifact",
        { rejectSymbolicLinks: true },
      ),
      file = await readFile(artifactPath),
      bytes = new Uint8Array(file.buffer, file.byteOffset, file.byteLength);
    if (bytes.length !== artifact.bytes || digest(bytes) !== artifact.hash)
      throw new Error(`ARTIFACT_MISMATCH: ${artifact.path}`);
    artifacts.set(artifact.path, bytes);
  }
  if (manifest.wasm) {
    const bytes = artifacts.get(manifest.wasm.path);
    if (!bytes || digest(bytes) !== manifest.wasm.wasmHash)
      throw new Error("ARTIFACT_MISMATCH: effects Wasm");
    assertEffectsWasm(bytes);
  }
  return { manifest, artifacts };
}
