import type { CheckedEffectsModuleProgram } from "./llang-module-effects-loader";

const literal = (value: unknown) => JSON.stringify(value, null, 2);

export function emitEffectsModuleJsonc(
  program: CheckedEffectsModuleProgram,
): string {
  return `${JSON.stringify(program.source, null, 2)}\n`;
}

export function emitEffectsModuleTypeScript(
  program: CheckedEffectsModuleProgram,
): string {
  const steps = program.source.steps
    .map(
      (step) => `  {
    const response = await host.invoke(${literal({
      operation: step.operation,
      version: step.version,
      payload: step.payload,
    })});
    if (!response.ok) throw new EffectsOperationError(response.error);
    ${
      step.combine === "replace"
        ? "accumulator = checkedI32(response.value);"
        : "accumulator = checkedI32(accumulator + checkedI32(response.value));"
    }
  }`,
    )
    .join("\n");
  return `// Generated by L-Lang module-effects-v1. Do not edit.
export type EffectsRequest = Readonly<{
  operation: string;
  version: number;
  payload: number;
}>;
export type EffectsResponse =
  | Readonly<{ ok: true; value: number }>
  | Readonly<{ ok: false; error: Readonly<{ code: string; outcome?: "known" | "unknown" }> }>;
export interface EffectsHost {
  invoke(request: EffectsRequest): Promise<EffectsResponse>;
}
export class EffectsOperationError extends Error {
  constructor(readonly detail: Readonly<{ code: string; outcome?: "known" | "unknown" }>) {
    super(detail.code);
  }
}
const checkedI32 = (value: number): number => {
  if (!Number.isInteger(value) || value < -2147483648 || value > 2147483647)
    throw new Error("ARITHMETIC_OVERFLOW");
  return value;
};
export async function ${program.source.entry}(host: EffectsHost): Promise<number> {
  let accumulator = ${program.source.initial};
${steps}
  return accumulator;
}
`;
}
