import { posix } from "node:path";
import type {
  CheckedFunction,
  CheckedModuleProgram,
  ModuleExpression,
  ModuleSource,
  ResolvedType,
} from "./llang-module-ir";
import { resolveImportId } from "./llang-module-ir";

function safe(value: string): string {
  return `_${Buffer.from(value).toString("hex")}`;
}
function emitType(type: ResolvedType): string {
  return type.kind === "boolean"
    ? "boolean"
    : `{ ${type.fields.map((field) => `${JSON.stringify(field)}: boolean`).join("; ")} }`;
}
function emitExpression(
  expression: ModuleExpression,
  fn: CheckedFunction,
): string {
  switch (expression.kind) {
    case "literal":
      return String(expression.value);
    case "param":
      return safe(`p:${expression.name}`);
    case "field":
      return `${safe(`p:${expression.base.name}`)}[${JSON.stringify(expression.name)}]`;
    case "not":
      return `!(${emitExpression(expression.condition, fn)})`;
    case "all":
      return `(${expression.conditions.map((x) => emitExpression(x, fn)).join(" && ")})`;
    case "any":
      return `(${expression.conditions.map((x) => emitExpression(x, fn)).join(" || ")})`;
    case "equals":
      return `(${emitExpression(expression.left, fn)} === ${emitExpression(expression.right, fn)})`;
    case "call": {
      const target = fn.callees[expression.callee];
      if (!target) throw new Error("unresolved call");
      return `${safe(target)}(${expression.arguments.map((x) => emitExpression(x, fn)).join(", ")})`;
    }
  }
}

export function emitModuleTypeScript(program: CheckedModuleProgram): string {
  const entry = program.functions.find((fn) => fn.symbol === program.entry);
  if (entry?.parameters[0]?.type.kind !== "record")
    throw new Error("invalid entry");
  const functions = program.functions
    .map(
      (fn) =>
        `function ${safe(fn.symbol)}(${fn.parameters.map((p) => `${safe(`p:${p.name}`)}: ${emitType(p.type)}`).join(", ")}): boolean {\n  return ${emitExpression(fn.body, fn)};\n}`,
    )
    .join("\n\n");
  const fields = entry.parameters[0].type.fields;
  return `// Generated by L-Lang module-bool-v1. Do not edit.\n${functions}\n\nexport type EntryInput = ${emitType(entry.parameters[0].type)};\nfunction invalidInput(message: string): never {\n  const error = new TypeError(\`INVALID_INPUT: \${message}\`) as TypeError & { code: string };\n  error.code = "INVALID_INPUT";\n  throw error;\n}\nexport function evaluate(input: EntryInput): boolean {\n  if (typeof input !== "object" || input === null || Array.isArray(input) || (Object.getPrototypeOf(input) !== Object.prototype && Object.getPrototypeOf(input) !== null)) invalidInput("expected a data record");\n  const expected = ${JSON.stringify(fields)};\n  const descriptors = Object.getOwnPropertyDescriptors(input);\n  if (Object.getOwnPropertySymbols(input).length || Object.keys(descriptors).length !== expected.length || Object.entries(descriptors).some(([key, descriptor]) => !expected.includes(key) || !("value" in descriptor))) invalidInput("fields do not match");\n  if (expected.some((key) => typeof descriptors[key]?.value !== "boolean")) invalidInput("fields must be boolean");\n  return ${safe(program.entry)}(input);\n}\n`;
}

function generatedPath(id: string): string {
  return `${id}.llang.jsonc`;
}
export function emitModuleJsonc(
  program: CheckedModuleProgram,
): Map<string, string> {
  const output = new Map<string, string>();
  for (const module of program.modules) {
    const importsByTarget = new Map<
      string,
      ModuleSource["imports"][number]["bindings"]
    >();
    for (const item of module.source.imports) {
      const target = resolveImportId(module.id, item.from),
        bindings = importsByTarget.get(target) ?? [];
      bindings.push(...item.bindings);
      importsByTarget.set(target, bindings);
    }
    const source: ModuleSource = {
      language: "l-lang",
      version: 2,
      kind: "module",
      profile: "module-bool-v1",
      ...(module.source.description === undefined
        ? {}
        : { description: module.source.description }),
      imports: [...importsByTarget]
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([target, bindings]) => {
          let from = posix.relative(
            posix.dirname(generatedPath(module.id)),
            generatedPath(target),
          );
          if (!from.startsWith(".")) from = `./${from}`;
          return {
            from,
            bindings: [...bindings].sort((left, right) =>
              `${left.kind}\0${left.name}\0${left.as}`.localeCompare(
                `${right.kind}\0${right.name}\0${right.as}`,
              ),
            ),
          };
        }),
      types: module.source.types
        .map((type) => ({
          name: type.name,
          export: type.export,
          kind: "record" as const,
          fields: [...type.fields].sort((left, right) =>
            left.name.localeCompare(right.name),
          ),
        }))
        .sort((left, right) => left.name.localeCompare(right.name)),
      functions: module.source.functions
        .map((fn) => ({
          name: fn.name,
          export: fn.export,
          parameters: fn.parameters.map((parameter) => ({
            name: parameter.name,
            type:
              parameter.type === "boolean"
                ? ("boolean" as const)
                : { ref: parameter.type.ref },
          })),
          returns: "boolean" as const,
          body: fn.body,
        }))
        .sort((left, right) => left.name.localeCompare(right.name)),
    };
    output.set(
      generatedPath(module.id),
      `${JSON.stringify(source, null, 2)}\n`,
    );
  }
  return output;
}
