import { renderPredicateExpression } from "./generator";
import type { LlangProgram } from "./llang-program";
import type { WasmField } from "./wasm-contract";

export const LLANG_PREDICATE_PROJECTION_VERSION = 1 as const;

function fieldType(field: WasmField): string {
  const base =
    field.kind === "boolean"
      ? "boolean"
      : field.kind === "enum"
        ? field.values.map((value) => JSON.stringify(value)).join(" | ")
        : "string";
  return [
    base,
    field.nullable ? "null" : "",
    field.undefinable ? "undefined" : "",
  ]
    .filter(Boolean)
    .join(" | ");
}

function renderOwnProperty(parameter: string, property: string[]): string {
  if (property.length !== 1)
    throw new Error("predicate inspection supports one property segment");
  return `ownValue(${parameter}, ${JSON.stringify(property[0])})`;
}

/** Generates a deterministic, self-contained view of the checked predicate. */
export function generateLlangPredicateProjection(
  program: LlangProgram,
): string {
  if (program.profile !== "predicate-i32-v1")
    throw new Error("unsupported predicate projection profile");
  const fields = program.contract.fields.map(
    (field) =>
      `  ${JSON.stringify(field.name)}${field.optional ? "?" : ""}: ${fieldType(field)};`,
  );
  const expression = renderPredicateExpression(
    program.body,
    "input",
    1,
    renderOwnProperty,
  );
  return [
    "// Generated by L-Lang capability inspection. Do not edit.",
    "// 契約を満たす入力に対する判定ロジック。入力検査はL-Lang runtimeの責務です。",
    `// Projection format version: ${LLANG_PREDICATE_PROJECTION_VERSION}`,
    "",
    "export type Input = {",
    ...fields,
    "};",
    "",
    "function ownValue<T extends object, K extends keyof T>(",
    "  input: T,",
    "  key: K,",
    "): T[K] | undefined {",
    "  const descriptor = Object.getOwnPropertyDescriptor(input, key);",
    '  return descriptor && "value" in descriptor ? descriptor.value : undefined;',
    "}",
    "",
    "export function evaluate(input: Input): boolean {",
    `  return ${expression};`,
    "}",
    "",
  ].join("\n");
}
