const identifierPattern = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export function generateStaticJudgmentConstant(
  judgmentName: string,
  value: boolean,
): string {
  if (!identifierPattern.test(judgmentName)) {
    throw new Error(`Static Judgment name must be a valid identifier: ${judgmentName}`);
  }
  return [
    "// Generated by the semantic compiler. Do not edit.",
    `export const ${judgmentName} = ${String(value)} as const;`,
    "",
  ].join("\n");
}
