import { describe, expect, test } from "bun:test";

import { generateStaticJudgmentConstant } from "./static-judgment-generator";
import {
  buildStaticJudgmentRequest,
  parseStaticJudgmentResolution,
  STATIC_JUDGMENT_PROMPT_VERSION,
} from "./static-judgment";

describe("static judgment contract", () => {
  test("parses resolved true and false values", () => {
    expect(parseStaticJudgmentResolution({
      outcome: "resolved",
      value: true,
      diagnostics: [],
    })).toEqual({ outcome: "resolved", value: true, diagnostics: [] });
    expect(parseStaticJudgmentResolution({
      outcome: "resolved",
      value: false,
      diagnostics: ["the value conflicts with the Concept"],
    })).toEqual({
      outcome: "resolved",
      value: false,
      diagnostics: ["the value conflicts with the Concept"],
    });
  });

  test("accepts unresolved only with null and rejects malformed combinations", () => {
    expect(parseStaticJudgmentResolution({
      outcome: "unresolved",
      value: null,
      diagnostics: ["essential evidence is missing"],
    })).toEqual({
      outcome: "unresolved",
      value: null,
      diagnostics: ["essential evidence is missing"],
    });
    expect(() => parseStaticJudgmentResolution({
      outcome: "resolved",
      value: null,
      diagnostics: [],
    })).toThrow("must have a boolean value");
    expect(() => parseStaticJudgmentResolution({
      outcome: "unresolved",
      value: false,
      diagnostics: [],
    })).toThrow("must have a null value");
    expect(() => parseStaticJudgmentResolution({
      outcome: "resolved",
      value: true,
      diagnostics: [],
      extra: "not allowed",
    })).toThrow("must contain exactly");
  });

  test("builds a non-persisted structured request with separated source blocks", () => {
    expect(STATIC_JUDGMENT_PROMPT_VERSION).toBe("static-judgment-v1");
    const request = buildStaticJudgmentRequest({
      model: "gpt-5.4-mini",
      conceptId: "animal.cat",
      conceptSpecification: "A biological domesticated cat.",
      staticValue: "A small calico animal that meows.",
      judgmentName: "mikeIsCat",
    }) as {
      store: boolean;
      input: string;
      text: { format: { strict: boolean; name: string } };
    };
    expect(request.store).toBe(false);
    expect(request.text.format).toMatchObject({
      strict: true,
      name: "static_judgment",
    });
    expect(request.input).toContain("<concept_specification>");
    expect(request.input).toContain("<static_value>");
  });

  test("generates only a deterministic boolean constant", () => {
    const generated = generateStaticJudgmentConstant("mikeIsCat", true);
    expect(generated).toBe(
      "// Generated by the semantic compiler. Do not edit.\n" +
      "export const mikeIsCat = true as const;\n",
    );
    expect(generateStaticJudgmentConstant("mikeIsCat", true)).toBe(generated);
    expect(generateStaticJudgmentConstant("mikeIsCat", false)).toContain(
      "false as const",
    );
    expect(generated).not.toMatch(/OPENAI|fetch|api-key|calico/);
    expect(() => generateStaticJudgmentConstant("not-valid!", true)).toThrow(
      "valid identifier",
    );
  });
});
