(module
  (memory (export "memory") 1)
  ;; All algorithms sort the same signed i32 keys in place at address zero.
  (func $get (param $i i32) (result i32)
    (i32.load (i32.shl (local.get $i) (i32.const 2))))
  (func $put (param $i i32) (param $v i32)
    (i32.store (i32.shl (local.get $i) (i32.const 2)) (local.get $v)))
  (func $swap (param $a i32) (param $b i32) (local $v i32)
    (local.set $v (call $get (local.get $a)))
    (call $put (local.get $a) (call $get (local.get $b)))
    (call $put (local.get $b) (local.get $v)))
  (func (export "insertion") (param $n i32)
    (local $i i32) (local $j i32) (local $v i32)
    (local.set $i (i32.const 1))
    (block $done (loop $outer
      (br_if $done (i32.ge_s (local.get $i) (local.get $n)))
      (local.set $v (call $get (local.get $i)))
      (local.set $j (local.get $i))
      (block $placed (loop $inner
        (br_if $placed (i32.le_s (local.get $j) (i32.const 0)))
        (br_if $placed (i32.le_s (call $get (i32.sub (local.get $j) (i32.const 1))) (local.get $v)))
        (call $put (local.get $j) (call $get (i32.sub (local.get $j) (i32.const 1))))
        (local.set $j (i32.sub (local.get $j) (i32.const 1)))
        (br $inner)))
      (call $put (local.get $j) (local.get $v))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $outer))))
  (func (export "selection") (param $n i32)
    (local $i i32) (local $j i32) (local $min i32)
    (block $done (loop $outer
      (br_if $done (i32.ge_s (local.get $i) (i32.sub (local.get $n) (i32.const 1))))
      (local.set $min (local.get $i))
      (local.set $j (i32.add (local.get $i) (i32.const 1)))
      (block $scanned (loop $inner
        (br_if $scanned (i32.ge_s (local.get $j) (local.get $n)))
        (if (i32.lt_s (call $get (local.get $j)) (call $get (local.get $min)))
          (then (local.set $min (local.get $j))))
        (local.set $j (i32.add (local.get $j) (i32.const 1)))
        (br $inner)))
      (call $swap (local.get $i) (local.get $min))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $outer))))
  (func (export "bubble") (param $n i32)
    (local $end i32) (local $i i32) (local $changed i32)
    (local.set $end (i32.sub (local.get $n) (i32.const 1)))
    (block $done (loop $outer
      (br_if $done (i32.le_s (local.get $end) (i32.const 0)))
      (local.set $changed (i32.const 0))
      (local.set $i (i32.const 0))
      (block $scanned (loop $inner
        (br_if $scanned (i32.ge_s (local.get $i) (local.get $end)))
        (if (i32.gt_s (call $get (local.get $i)) (call $get (i32.add (local.get $i) (i32.const 1))))
          (then
            (call $swap (local.get $i) (i32.add (local.get $i) (i32.const 1)))
            (local.set $changed (i32.const 1))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $inner)))
      (br_if $done (i32.eqz (local.get $changed)))
      (local.set $end (i32.sub (local.get $end) (i32.const 1)))
      (br $outer))))
  (func (export "shell") (param $n i32)
    (local $gap i32) (local $i i32) (local $j i32) (local $v i32)
    (local.set $gap (i32.div_s (local.get $n) (i32.const 2)))
    (block $done (loop $gaps
      (br_if $done (i32.le_s (local.get $gap) (i32.const 0)))
      (local.set $i (local.get $gap))
      (block $pass (loop $outer
        (br_if $pass (i32.ge_s (local.get $i) (local.get $n)))
        (local.set $v (call $get (local.get $i)))
        (local.set $j (local.get $i))
        (block $placed (loop $inner
          (br_if $placed (i32.lt_s (local.get $j) (local.get $gap)))
          (br_if $placed (i32.le_s (call $get (i32.sub (local.get $j) (local.get $gap))) (local.get $v)))
          (call $put (local.get $j) (call $get (i32.sub (local.get $j) (local.get $gap))))
          (local.set $j (i32.sub (local.get $j) (local.get $gap)))
          (br $inner)))
        (call $put (local.get $j) (local.get $v))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $outer)))
      (local.set $gap (i32.div_s (local.get $gap) (i32.const 2)))
      (br $gaps))))
  (func $sift (param $root i32) (param $n i32) (local $child i32)
    (block $done (loop $loop
      (local.set $child (i32.add (i32.mul (local.get $root) (i32.const 2)) (i32.const 1)))
      (br_if $done (i32.ge_s (local.get $child) (local.get $n)))
      (if (i32.lt_s (i32.add (local.get $child) (i32.const 1)) (local.get $n))
        (then (if (i32.lt_s (call $get (local.get $child)) (call $get (i32.add (local.get $child) (i32.const 1))))
          (then (local.set $child (i32.add (local.get $child) (i32.const 1)))))))
      (br_if $done (i32.ge_s (call $get (local.get $root)) (call $get (local.get $child))))
      (call $swap (local.get $root) (local.get $child))
      (local.set $root (local.get $child))
      (br $loop))))
  (func (export "heap") (param $n i32) (local $i i32) (local $end i32)
    (local.set $i (i32.sub (i32.div_s (local.get $n) (i32.const 2)) (i32.const 1)))
    (block $built (loop $build
      (br_if $built (i32.lt_s (local.get $i) (i32.const 0)))
      (call $sift (local.get $i) (local.get $n))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (br $build)))
    (local.set $end (i32.sub (local.get $n) (i32.const 1)))
    (block $done (loop $extract
      (br_if $done (i32.le_s (local.get $end) (i32.const 0)))
      (call $swap (i32.const 0) (local.get $end))
      (call $sift (i32.const 0) (local.get $end))
      (local.set $end (i32.sub (local.get $end) (i32.const 1)))
      (br $extract))))
)
